//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicService
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient
    {
        public patient()
        {
            this.consultation = new HashSet<consultation>();
        }
    
        public int patientID { get; set; }
        public string name { get; set; }
        public int idCardNumber { get; set; }
        public int PIN { get; set; }
        public System.DateTime birthDate { get; set; }
    
        public virtual ICollection<consultation> consultation { get; set; }
    }
}
