//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicService
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.consultation = new HashSet<consultation>();
        }
    
        public int userID { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string function { get; set; }
    
        public virtual ICollection<consultation> consultation { get; set; }
    }
}
